# Generated by Django 5.0.1 on 2024-01-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charity_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('fundacja', 'Fundacja'), ('organizacja_pozarzadowa', 'Organizacja pozarządowa'), ('zbiorka_lokalna', 'Zbiórka lokalna')], default='fundacja', max_length=50)),
                ('categories', models.ManyToManyField(to='Charity_app.category')),
            ],
        ),
    ]
