# Generated by Django 5.0.1 on 2024-01-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Charity_app', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
