# Generated by Django 5.0.1 on 2024-01-14 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Charity_app', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
